name: Run build and lint
on:
  workflow_dispatch:
  pull_request:

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn build
          yarn lint
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "${{ github.event_name }}"
      - run: echo "${{ github.ref }}"
      - run: echo "${{ github.head_ref }}"
      - run: echo "${{ github.base_ref }}"
      - run: echo "${{ github.event.pull_request.head.ref }}"
      - run: echo "${{ github.event.pull_request.base.ref }}"
  tests:
    # runs only on pull requests to master or develop branches
    if: |
      github.event_name == 'pull_request' &&
      (github.base_ref == 'master' || github.base_ref == 'develop')
    # Operating system to run job on
    runs-on: ubuntu-latest
    needs:
      - lint-build
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      # Build the app using cypress
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn preview --port 3000
          wait-on: http://localhost:3000/
          config_file: cypress.json
          spec: 'cypress/integration/**/*'
        env:
          CYPRESS_baseUrl: http://localhost:3000/
          CYPRESS_username: ${{secrets.CYPRESS_USERNAME}}
          CYPRESS_password: ${{secrets.CYPRESS_PASSWORD}}
          CYPRESS_apiUrl: ${{secrets.CYPRESS_API_URL}}
  deploy-draft:
    # runs only on pull requests to develop branches
    if: |
      github.event_name == 'pull_request' &&
      github.base_ref == 'develop'
    # Operating system to run job on
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      # ... your other build steps to produce a build directory
      # e.g. `npm run build` for create-react-app dd
      # Install NodeJS
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies with yarn and build
        run: yarn install && yarn build

      - name: Deploy draft to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './dist'
          draft: true
          comment-on-commit: true
          comment-on-pull-request: true
  deploy:
    # runs only on push to master branch
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/master'
    # Operating system to run job on
    runs-on: ubuntu-latest
    needs:
      - tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      # ... your other build steps to produce a build directory
      # e.g. `npm run build` for create-react-app
      # Install NodeJS
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install dependencies with yarn and build
        run: yarn install && yarn build

      - name: Deploy to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './dist'
          comment-on-commit: true
